server:
  port: 80

openapis: 
  naver: 
    name: 네이버
    limit: 25000
    urls: 
      web: https://openapi.naver.com/v1/search/webkr.json
      blog: https://openapi.naver.com/v1/search/blog.json
      news: https://openapi.naver.com/v1/search/news.json
    client-id: LVS8txbm57fRHlZCzW7L
    client-secret: DXoSIRxvIf
  
  kakao: 
    name: 다음(카카오)
    restapi-key: f50dfeeb7e9797d4f02d9eb693d594d8
    urls: 
      web: https://dapi.kakao.com/v2/search/web
      blog: https://dapi.kakao.com/v2/search/blog
  

spring:
  elasticsearch:
    cluster-name: docker-cluster
    host: localhost
    port: 9300
  aop:
    proxy-target-class: false
